In [29]:
import numpy as np
import pandas as pd

In [5]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
baslangic_degeri = 0
bitis_degeri = 20
aralik = 5

In [8]:
np.arange(baslangic_degeri,bitis_degeri,aralik)

array([ 0,  5, 10, 15])

In [11]:
# 3 uncu deger olusacak deger sayisi
np.linspace(0,15,3)

array([ 0. ,  7.5, 15. ])

In [14]:
#0 ile 1 arasinda 5 deger olusturur
np.random.rand(5)

array([0.45357804, 0.60668294, 0.75692939, 0.32992156, 0.73600804])

In [16]:
np.random.rand(2,3)

array([[0.11345281, 0.02307223, 0.07753118],
       [0.33097808, 0.08937616, 0.02871648]])

In [19]:
#ortalamasi 1 standat sapmasi 1 olan 3 3 luk matriks
np.random.normal(0,1,(3,3))

array([[ 0.91880254, -3.11258683,  0.67622322],
       [-0.45297845,  0.57973255, -0.24510823],
       [-0.14064341,  2.48978056,  0.80149141]])

In [23]:
#random bir sayi uretir 0 ile 10 arasi
np.random.randint(0,10)

0

In [24]:
#3 girdi satir sutuna bagli olan bir degerdir
np.random.randint(0,10,(3,3))

array([[3, 3, 3],
       [9, 7, 9],
       [2, 9, 9]])

In [32]:
data = np.random.randint(0,20,(2,3))
df =pd.DataFrame(data,columns=["sayi1","sayi2","sayi3"])

In [34]:
df

,sayi1,sayi2,sayi3
0,5,18,2
1,0,11,5


In [36]:
df["toplami"] = (df.sayi1 + df.sayi2 + df.sayi3)
df["ortalama"] = (df.sayi1 + df.sayi2 + df.sayi3)/3

In [40]:
df["sayi1"].max()

5

In [45]:
def find_max():
    max = 0
    for i in df.columns:
        print(i)
        for j in df[i]:
            print(j)
            if j > max:
                max = j
    return max

In [46]:
find_max()

sayi1
5
0
sayi2
18
11
sayi3
2
5
toplami
25
16
ortalama
8.333333333333334
5.333333333333333


0